In [34]:
import numpy as np
import pandas as pd
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

In [35]:
file = pd.read_csv(r"C:\Users\rahul\Desktop\Offshore\PubSec-Info-Assistant-Offshore\backend\approaches\project_name_district_apartment&unit_type_eng_v3.csv")
df = file[['project_id', 'project_name_eng', 'TotalUnitsCount',
       'AvailableUnitsCount', 'city_id', 'region_id', 'district_eng',
       'property_year_of_built', 'BookingsCount', 'PercentageUnitsBooked',
       'active_payment_by_cash', 'active_payment_by_loan', 'project_latitude',
       'project_longitude', 'publish_date', 'code', 'completion_percentage',
       'mega_project_id', 'unit_code', 'moh_price', 'price', 'block_number',
       'apartment_number', 'building_number', 'unit_size', 'living_area',
       'floor', 'floor_count', 'unit_type_eng', 'bedroom_count', 'bathroom_count',
       'selections_count', 'bookings_count', 'comment', 'apartment_type_eng',
       'zone_number', 'number_of_rooms', 'master_bedroom_size',
       'living_room_size', 'kitchen_size', 'guestroom_size', 'FirstPrice',
       'partners', 'web', 'mobile', 'beneficiary', 'non_bene',
       'construction_status']].copy()
df.head()

,project_id,project_name_eng,TotalUnitsCount,AvailableUnitsCount,city_id,region_id,district_eng,property_year_of_built,BookingsCount,PercentageUnitsBooked,active_payment_by_cash,active_payment_by_loan,project_latitude,project_longitude,publish_date,code,completion_percentage,mega_project_id,unit_code,moh_price,price,block_number,apartment_number,building_number,unit_size,living_area,floor,floor_count,unit_type_eng,bedroom_count,bathroom_count,selections_count,bookings_count,comment,apartment_type_eng,zone_number,number_of_rooms,master_bedroom_size,living_room_size,kitchen_size,guestroom_size,FirstPrice,partners,web,mobile,beneficiary,non_bene,construction_status
0,77,Tabuk - Modern Homes - Durat Tabuk,243,115,41,11,Summer,NaN,1046,50.617284,1,1,28.455361,36.51625,2021-01-25,01-11-0003,0.0,NaN,11-1104-2608-05-00000000802,267922.79796,330190.0,T5,T5-D-G-2,D,152.5,19.76,0,NaN,Apartment,3,4,0,0,نموذج 3-3,Apartment,1,3.0,18.7,16.0,8.8,23.0,267922.79796,1,1,1,0,0,0
1,77,Tabuk - Modern Homes - Durat Tabuk,243,115,41,11,Summer,NaN,1046,50.617284,1,1,28.455361,36.51625,2021-01-25,01-11-0003,0.0,NaN,11-1104-2608-05-00000000813,305695.52029,376638.0,T5,T5-D-3-13,D,174.0,21.92,3,NaN,Apartment,3,4,0,0,نموذج 3-3,Apartment,1,3.0,18.7,13.6,8.8,15.6,344023.00000,1,1,1,0,0,0
2,77,Tabuk - Modern Homes - Durat Tabuk,243,115,41,11,Summer,NaN,1046,50.617284,1,1,28.455361,36.51625,2021-01-25,01-11-0003,0.0,NaN,11-1104-2608-05-00000000817,305695.52029,376638.0,T5,T5-D-4-17,D,174.0,21.92,4,NaN,Apartment,3,4,0,0,نموذج 3-3,Apartment,1,3.0,18.7,13.6,8.8,15.6,305695.52029,1,1,1,0,0,0
3,77,Tabuk - Modern Homes - Durat Tabuk,243,115,41,11,Summer,NaN,1046,50.617284,1,1,28.455361,36.51625,2021-01-25,01-11-0003,0.0,NaN,11-1104-2608-05-00000000821,305695.52029,376638.0,T5,T5-D-5-21,D,174.0,21.92,5,NaN,Apartment,3,4,0,0,نموذج 3-3,Apartment,1,3.0,18.7,13.6,8.8,15.6,305695.52029,1,1,1,0,0,0
4,77,Tabuk - Modern Homes - Durat Tabuk,243,115,41,11,Summer,NaN,1046,50.617284,1,1,28.455361,36.51625,2021-01-25,01-11-0003,0.0,NaN,11-1104-2608-05-00000000825,305695.52029,376638.0,T5,T5-D-6-25,D,174.0,21.92,6,NaN,Apartment,3,4,0,0,نموذج 3-3,Apartment,1,3.0,18.7,13.6,8.8,15.6,305695.52029,1,1,1,0,0,0

In [36]:
file.head()

,Unnamed: 0,project_id,project_name,TotalUnitsCount,AvailableUnitsCount,city_id,region_id,district,property_year_of_built,BookingsCount,PercentageUnitsBooked,active_payment_by_cash,active_payment_by_loan,project_latitude,project_longitude,publish_date,code,completion_percentage,mega_project_id,unit_code,moh_price,price,block_number,apartment_number,building_number,unit_size,living_area,floor,floor_count,unit_type,bedroom_count,bathroom_count,selections_count,bookings_count,comment,apartment_type,zone_number,number_of_rooms,master_bedroom_size,living_room_size,kitchen_size,guestroom_size,FirstPrice,partners,web,mobile,beneficiary,non_bene,construction_status,project_name_eng,district_eng,unit_type_eng,apartment_type_eng
0,0,77,تبوك - منازل العصرية - درة تبوك,243,115,41,11,المصيف,NaN,1046,50.617284,1,1,28.455361,36.51625,2021-01-25,01-11-0003,0.0,NaN,11-1104-2608-05-00000000802,267922.79796,330190.0,T5,T5-D-G-2,D,152.5,19.76,0,NaN,شقة,3,4,0,0,نموذج 3-3,شقة,1,3.0,18.7,16.0,8.8,23.0,267922.79796,1,1,1,0,0,0,Tabuk - Modern Homes - Durat Tabuk,Summer,Apartment,Apartment
1,1,77,تبوك - منازل العصرية - درة تبوك,243,115,41,11,المصيف,NaN,1046,50.617284,1,1,28.455361,36.51625,2021-01-25,01-11-0003,0.0,NaN,11-1104-2608-05-00000000813,305695.52029,376638.0,T5,T5-D-3-13,D,174.0,21.92,3,NaN,شقة,3,4,0,0,نموذج 3-3,شقة,1,3.0,18.7,13.6,8.8,15.6,344023.00000,1,1,1,0,0,0,Tabuk - Modern Homes - Durat Tabuk,Summer,Apartment,Apartment
2,2,77,تبوك - منازل العصرية - درة تبوك,243,115,41,11,المصيف,NaN,1046,50.617284,1,1,28.455361,36.51625,2021-01-25,01-11-0003,0.0,NaN,11-1104-2608-05-00000000817,305695.52029,376638.0,T5,T5-D-4-17,D,174.0,21.92,4,NaN,شقة,3,4,0,0,نموذج 3-3,شقة,1,3.0,18.7,13.6,8.8,15.6,305695.52029,1,1,1,0,0,0,Tabuk - Modern Homes - Durat Tabuk,Summer,Apartment,Apartment
3,3,77,تبوك - منازل العصرية - درة تبوك,243,115,41,11,المصيف,NaN,1046,50.617284,1,1,28.455361,36.51625,2021-01-25,01-11-0003,0.0,NaN,11-1104-2608-05-00000000821,305695.52029,376638.0,T5,T5-D-5-21,D,174.0,21.92,5,NaN,شقة,3,4,0,0,نموذج 3-3,شقة,1,3.0,18.7,13.6,8.8,15.6,305695.52029,1,1,1,0,0,0,Tabuk - Modern Homes - Durat Tabuk,Summer,Apartment,Apartment
4,4,77,تبوك - منازل العصرية - درة تبوك,243,115,41,11,المصيف,NaN,1046,50.617284,1,1,28.455361,36.51625,2021-01-25,01-11-0003,0.0,NaN,11-1104-2608-05-00000000825,305695.52029,376638.0,T5,T5-D-6-25,D,174.0,21.92,6,NaN,شقة,3,4,0,0,نموذج 3-3,شقة,1,3.0,18.7,13.6,8.8,15.6,305695.52029,1,1,1,0,0,0,Tabuk - Modern Homes - Durat Tabuk,Summer,Apartment,Apartment

In [43]:
district_translation = {
    "المصيف": "Al-Musayyaf",
    "التعاون": "Al-Ta'awun",
    "الراقي": "Al-Raqi",
    "غرب الدمام": "West Dammam",
    "حي الأمير عبدالمجيد": "Prince Abdulmajid District",
    "الفواز": "Al-Fawaz",
    "السيل الصغير": "As-Sail Al-Saghir",
    "الضبط": "Al-Dabt",
    "حي الحزم": "Al-Hazm District",
    "العهن": "Al-Ihan",
    "المطار": "Al-Matar (Airport)",
    "النوارية": "Al-Nuwariya",
    "أبحر الشمالية - الصواري": "North Obhur - Al-Sawari",
    "إسكان الدمام الشمالي": "North Dammam Housing",
    "الرمال": "Al-Rimal",
    "السكب": "Al-Sakb",
    "عين السيح": "Ain Al-Saih",
    "الامواج": "Al-Amwaj",
    "الهياثم": "Al-Hayathim",
    "حي النزهة": "Al-Nuzha District",
    "الشعلة": "Al-Sha'ala",
    "المونسية": "Al-Munsiya",
    "حي الحمراء": "Al-Hamra District",
    "الصواري": "Al-Sawari",
    "الروضة": "Al-Rawdah",
    "العوالي": "Al-Awali",
    "الحزم ": "Al-Hazm",
    "الريان": "Al-Rayan",
    "التوفيق": "Al-Tawfiq",
    "الواحة": "Al-Waha",
    "اشبيليه الثاني المجاورة الثانية": "Second Ishbiliyah - Second Neighbor",
    "اشبيليه الثاني المجاورة الاولى": "Second Ishbiliyah - First Neighbor",
    "المنتزه": "Al-Muntazah",
    "حي الضباب": "Al-Dhabaab District",
    "النرجس": "Al-Narjis",
    "الضاحية الجنوبية": "Southern Suburb",
    "البدرية": "Al-Badriya",
    "السفن": "Al-Sufun",
    "مجتمع المكيمن": "Al-Mukaymin Community",
    "حي احد": "Uhud District",
    "الحمراء": "Al-Hamra",
    "العارض ": "Al-Aarid",
    "القدس": "Al-Quds",
    "الجصة": "Al-Jassa",
    "ولي العهد": "Crown Prince",
    "الأندلس": "Al-Andalus",
    "المحمدية": "Al-Mohamadiyah",
    "قمرة": "Qumra",
    "ضاحية الواجهة": "Al-Wajha Suburb",
    "ضاحية الجوهرة": "Al-Jawhara Suburb",
    "الفرسان": "Al-Fursan",
    "الجنادرية ": "Al-Janadriyah",
    "الجنادرية": "Al-Janadriyah",
    "اشبيليا": "Ishbiliyah",
    "العاقول": "Al-Aqool",
    "الضاحية الشمالية": "Northern Suburb",
    "صفوى ": "Safwa",
    "صفوى": "Safwa",
    "ضاحية الفرسان": "Al-Fursan Suburb",
    "عرقة": "Arqa",
    "الزهراء": "Al-Zahraa",
    "البندرية": "Al-Bandariya",
    "الروابي": "Al-Rawabi",
    "المحمدية 3": "Al-Mohamadiyah 3",
    "اللؤلؤ": "Al-Lu'lu'",
    "الدوحة": "Al-Dawha",
    "القرينية": "Al-Qurainiyah",
    "السيف (مدينة ثروة)": "Al-Saif (Tharwa City)",
    "بوسحبل": "Bu Sabel",
    "شرق البحيرات": "East of Lakes",
    "البحيرات": "Al-Buhayrat (Lakes)",
    "ذهبان": "Dhahban",
    "الأمير فواز": "Prince Fawaz",
    "شرق البحيرات ": "East of Lakes",
    "الضاحية الجنوبية  ": "Southern Suburb",
    "الصدفة": "Al-Sadafa",
    "الراكة": "Al-Rakah",
    "الفبحاء": "Al-Fabha",
    "حي الجموات - منطقة العقيق": "Al-Jumawat District - Al-Aqiq Area",
    "ضاحية سدايم": "Sadayem Suburb",
    "الفيصلية": "Al-Faisaliyah",
    "حي الجنادرية / ضاحية الفرسان": "Al-Janadriyah District / Al-Fursan Suburb",
    "العرين": "Al-Areen",
    "سدايم": "Sadayem",
    "الشبيلي": "Al-Shubaily",
    "حي الملك فهد": "King Fahd District",
    "حي القرينية": "Al-Qurainiyah District",
    "المحلة الجديدة": "Al-Mahalla Al-Jadida",
    "الورود": "Al-Wurud",
    "حي الجنادرية": "Al-Janadriyah District",
    "حي الفيصلية": "Al-Faisaliyah District",
    "الصفا": "Al-Safa"
}
len(district_translation)

92

In [44]:
file['district_eng_gpt'] = file.district.apply(lambda x: district_translation.get(x, "unknown"))
file.head()

,Unnamed: 0,project_id,project_name,TotalUnitsCount,AvailableUnitsCount,city_id,region_id,district,property_year_of_built,BookingsCount,PercentageUnitsBooked,active_payment_by_cash,active_payment_by_loan,project_latitude,project_longitude,publish_date,code,completion_percentage,mega_project_id,unit_code,moh_price,price,block_number,apartment_number,building_number,unit_size,living_area,floor,floor_count,unit_type,bedroom_count,bathroom_count,selections_count,bookings_count,comment,apartment_type,zone_number,number_of_rooms,master_bedroom_size,living_room_size,kitchen_size,guestroom_size,FirstPrice,partners,web,mobile,beneficiary,non_bene,construction_status,project_name_eng,district_eng,unit_type_eng,apartment_type_eng,district_eng_gpt
0,0,77,تبوك - منازل العصرية - درة تبوك,243,115,41,11,المصيف,NaN,1046,50.617284,1,1,28.455361,36.51625,2021-01-25,01-11-0003,0.0,NaN,11-1104-2608-05-00000000802,267922.79796,330190.0,T5,T5-D-G-2,D,152.5,19.76,0,NaN,شقة,3,4,0,0,نموذج 3-3,شقة,1,3.0,18.7,16.0,8.8,23.0,267922.79796,1,1,1,0,0,0,Tabuk - Modern Homes - Durat Tabuk,Summer,Apartment,Apartment,Al-Musayyaf
1,1,77,تبوك - منازل العصرية - درة تبوك,243,115,41,11,المصيف,NaN,1046,50.617284,1,1,28.455361,36.51625,2021-01-25,01-11-0003,0.0,NaN,11-1104-2608-05-00000000813,305695.52029,376638.0,T5,T5-D-3-13,D,174.0,21.92,3,NaN,شقة,3,4,0,0,نموذج 3-3,شقة,1,3.0,18.7,13.6,8.8,15.6,344023.00000,1,1,1,0,0,0,Tabuk - Modern Homes - Durat Tabuk,Summer,Apartment,Apartment,Al-Musayyaf
2,2,77,تبوك - منازل العصرية - درة تبوك,243,115,41,11,المصيف,NaN,1046,50.617284,1,1,28.455361,36.51625,2021-01-25,01-11-0003,0.0,NaN,11-1104-2608-05-00000000817,305695.52029,376638.0,T5,T5-D-4-17,D,174.0,21.92,4,NaN,شقة,3,4,0,0,نموذج 3-3,شقة,1,3.0,18.7,13.6,8.8,15.6,305695.52029,1,1,1,0,0,0,Tabuk - Modern Homes - Durat Tabuk,Summer,Apartment,Apartment,Al-Musayyaf
3,3,77,تبوك - منازل العصرية - درة تبوك,243,115,41,11,المصيف,NaN,1046,50.617284,1,1,28.455361,36.51625,2021-01-25,01-11-0003,0.0,NaN,11-1104-2608-05-00000000821,305695.52029,376638.0,T5,T5-D-5-21,D,174.0,21.92,5,NaN,شقة,3,4,0,0,نموذج 3-3,شقة,1,3.0,18.7,13.6,8.8,15.6,305695.52029,1,1,1,0,0,0,Tabuk - Modern Homes - Durat Tabuk,Summer,Apartment,Apartment,Al-Musayyaf
4,4,77,تبوك - منازل العصرية - درة تبوك,243,115,41,11,المصيف,NaN,1046,50.617284,1,1,28.455361,36.51625,2021-01-25,01-11-0003,0.0,NaN,11-1104-2608-05-00000000825,305695.52029,376638.0,T5,T5-D-6-25,D,174.0,21.92,6,NaN,شقة,3,4,0,0,نموذج 3-3,شقة,1,3.0,18.7,13.6,8.8,15.6,305695.52029,1,1,1,0,0,0,Tabuk - Modern Homes - Durat Tabuk,Summer,Apartment,Apartment,Al-Musayyaf

In [46]:
df = file[['project_id', 'project_name_eng', 'TotalUnitsCount',
       'AvailableUnitsCount', 'city_id', 'region_id', 'district_eng_gpt',
       'property_year_of_built', 'BookingsCount', 'PercentageUnitsBooked',
       'active_payment_by_cash', 'active_payment_by_loan', 'project_latitude',
       'project_longitude', 'publish_date', 'code', 'completion_percentage',
       'mega_project_id', 'unit_code', 'moh_price', 'price', 'block_number',
       'apartment_number', 'building_number', 'unit_size', 'living_area',
       'floor', 'floor_count', 'unit_type_eng', 'bedroom_count', 'bathroom_count',
       'selections_count', 'bookings_count', 'comment', 'apartment_type_eng',
       'zone_number', 'number_of_rooms', 'master_bedroom_size',
       'living_room_size', 'kitchen_size', 'guestroom_size', 'FirstPrice',
       'partners', 'web', 'mobile', 'beneficiary', 'non_bene',
       'construction_status']].copy()
df.head()

,project_id,project_name_eng,TotalUnitsCount,AvailableUnitsCount,city_id,region_id,district_eng_gpt,property_year_of_built,BookingsCount,PercentageUnitsBooked,active_payment_by_cash,active_payment_by_loan,project_latitude,project_longitude,publish_date,code,completion_percentage,mega_project_id,unit_code,moh_price,price,block_number,apartment_number,building_number,unit_size,living_area,floor,floor_count,unit_type_eng,bedroom_count,bathroom_count,selections_count,bookings_count,comment,apartment_type_eng,zone_number,number_of_rooms,master_bedroom_size,living_room_size,kitchen_size,guestroom_size,FirstPrice,partners,web,mobile,beneficiary,non_bene,construction_status
0,77,Tabuk - Modern Homes - Durat Tabuk,243,115,41,11,Al-Musayyaf,NaN,1046,50.617284,1,1,28.455361,36.51625,2021-01-25,01-11-0003,0.0,NaN,11-1104-2608-05-00000000802,267922.79796,330190.0,T5,T5-D-G-2,D,152.5,19.76,0,NaN,Apartment,3,4,0,0,نموذج 3-3,Apartment,1,3.0,18.7,16.0,8.8,23.0,267922.79796,1,1,1,0,0,0
1,77,Tabuk - Modern Homes - Durat Tabuk,243,115,41,11,Al-Musayyaf,NaN,1046,50.617284,1,1,28.455361,36.51625,2021-01-25,01-11-0003,0.0,NaN,11-1104-2608-05-00000000813,305695.52029,376638.0,T5,T5-D-3-13,D,174.0,21.92,3,NaN,Apartment,3,4,0,0,نموذج 3-3,Apartment,1,3.0,18.7,13.6,8.8,15.6,344023.00000,1,1,1,0,0,0
2,77,Tabuk - Modern Homes - Durat Tabuk,243,115,41,11,Al-Musayyaf,NaN,1046,50.617284,1,1,28.455361,36.51625,2021-01-25,01-11-0003,0.0,NaN,11-1104-2608-05-00000000817,305695.52029,376638.0,T5,T5-D-4-17,D,174.0,21.92,4,NaN,Apartment,3,4,0,0,نموذج 3-3,Apartment,1,3.0,18.7,13.6,8.8,15.6,305695.52029,1,1,1,0,0,0
3,77,Tabuk - Modern Homes - Durat Tabuk,243,115,41,11,Al-Musayyaf,NaN,1046,50.617284,1,1,28.455361,36.51625,2021-01-25,01-11-0003,0.0,NaN,11-1104-2608-05-00000000821,305695.52029,376638.0,T5,T5-D-5-21,D,174.0,21.92,5,NaN,Apartment,3,4,0,0,نموذج 3-3,Apartment,1,3.0,18.7,13.6,8.8,15.6,305695.52029,1,1,1,0,0,0
4,77,Tabuk - Modern Homes - Durat Tabuk,243,115,41,11,Al-Musayyaf,NaN,1046,50.617284,1,1,28.455361,36.51625,2021-01-25,01-11-0003,0.0,NaN,11-1104-2608-05-00000000825,305695.52029,376638.0,T5,T5-D-6-25,D,174.0,21.92,6,NaN,Apartment,3,4,0,0,نموذج 3-3,Apartment,1,3.0,18.7,13.6,8.8,15.6,305695.52029,1,1,1,0,0,0

In [58]:
100*df.isnull().sum().sort_values(ascending=False)/df.shape[0]

comment                   87.46
property_year_of_built    72.10
mega_project_id           58.30
building_number           55.74
apartment_number          55.74
zone_number               36.42
kitchen_size              14.18
guestroom_size            14.16
master_bedroom_size       14.16
living_room_size          14.16
number_of_rooms           14.08
floor_count               12.66
project_longitude          2.50
project_latitude           2.50
FirstPrice                 0.82
selections_count           0.00
bathroom_count             0.00
bedroom_count              0.00
bookings_count             0.00
project_id                 0.00
apartment_type_eng         0.00
partners                   0.00
web                        0.00
mobile                     0.00
beneficiary                0.00
non_bene                   0.00
unit_type_eng              0.00
unit_size                  0.00
floor                      0.00
living_area                0.00
TotalUnitsCount            0.00
AvailableUnitsCount        0.00
city_id                    0.00
region_id                  0.00
district_eng_gpt           0.00
BookingsCount              0.00
PercentageUnitsBooked      0.00
active_payment_by_cash     0.00
active_payment_by_loan     0.00
publish_date               0.00
code                       0.00
completion_percentage      0.00
unit_code                  0.00
moh_price                  0.00
price                      0.00
block_number               0.00
project_name_eng           0.00
construction_status        0.00
dtype: float64

In [61]:
col_to_drop = ['comment', 'property_year_of_built', 'mega_project_id']
# df.drop(columns=col_to_drop, inplace=True)
df.rename(columns={"project_name_eng": "project_name", 
                   "district_eng_gpt": "district"}, inplace=True)
df.head(3)

,project_id,project_name,TotalUnitsCount,AvailableUnitsCount,city_id,region_id,district,BookingsCount,PercentageUnitsBooked,active_payment_by_cash,active_payment_by_loan,project_latitude,project_longitude,publish_date,code,completion_percentage,unit_code,moh_price,price,block_number,apartment_number,building_number,unit_size,living_area,floor,floor_count,unit_type_eng,bedroom_count,bathroom_count,selections_count,bookings_count,apartment_type_eng,zone_number,number_of_rooms,master_bedroom_size,living_room_size,kitchen_size,guestroom_size,FirstPrice,partners,web,mobile,beneficiary,non_bene,construction_status
0,77,Tabuk - Modern Homes - Durat Tabuk,243,115,41,11,Al-Musayyaf,1046,50.617284,1,1,28.455361,36.51625,2021-01-25,01-11-0003,0.0,11-1104-2608-05-00000000802,267922.79796,330190.0,T5,T5-D-G-2,D,152.5,19.76,0,NaN,Apartment,3,4,0,0,Apartment,1,3.0,18.7,16.0,8.8,23.0,267922.79796,1,1,1,0,0,0
1,77,Tabuk - Modern Homes - Durat Tabuk,243,115,41,11,Al-Musayyaf,1046,50.617284,1,1,28.455361,36.51625,2021-01-25,01-11-0003,0.0,11-1104-2608-05-00000000813,305695.52029,376638.0,T5,T5-D-3-13,D,174.0,21.92,3,NaN,Apartment,3,4,0,0,Apartment,1,3.0,18.7,13.6,8.8,15.6,344023.00000,1,1,1,0,0,0
2,77,Tabuk - Modern Homes - Durat Tabuk,243,115,41,11,Al-Musayyaf,1046,50.617284,1,1,28.455361,36.51625,2021-01-25,01-11-0003,0.0,11-1104-2608-05-00000000817,305695.52029,376638.0,T5,T5-D-4-17,D,174.0,21.92,4,NaN,Apartment,3,4,0,0,Apartment,1,3.0,18.7,13.6,8.8,15.6,305695.52029,1,1,1,0,0,0

In [62]:
df.to_csv(r"C:\Users\rahul\Desktop\Offshore\PubSec-Info-Assistant-Offshore\data\translated_file.csv", encoding='utf-8', index=False)

In [33]:
import pandas as pd
from googletrans import Translator

# Load the CSV file
# file_path = "your_file.csv"  # Replace with your file path
# df = pd.read_csv(file_path)

# Initialize the translator
translator = Translator()

# Define columns to translate
columns_to_translate = ['project_name', 'district', 'unit_type', 'apartment_type']

# Translate the columns
for column in columns_to_translate:
    if column in file.columns:
        col = column + "new"
        file[col] = file[column].apply(lambda x: translator.translate(str(x), src='ar', dest='en').text if pd.notnull(x) else x)

# Save the updated file
output_file = r"C:\Users\rahul\Desktop\Offshore\PubSec-Info-Assistant-Offshore\data\translated_file.csv"
file.to_csv(output_file, index=False)

print(f"Translation completed. Saved to {output_file}")

AttributeError: 'Translator' object has no attribute 'raise_Exception'

In [31]:
file.head()

,Unnamed: 0,project_id,project_name,TotalUnitsCount,AvailableUnitsCount,city_id,region_id,district,property_year_of_built,BookingsCount,PercentageUnitsBooked,active_payment_by_cash,active_payment_by_loan,project_latitude,project_longitude,publish_date,code,completion_percentage,mega_project_id,unit_code,moh_price,price,block_number,apartment_number,building_number,unit_size,living_area,floor,floor_count,unit_type,bedroom_count,bathroom_count,selections_count,bookings_count,comment,apartment_type,zone_number,number_of_rooms,master_bedroom_size,living_room_size,kitchen_size,guestroom_size,FirstPrice,partners,web,mobile,beneficiary,non_bene,construction_status,project_name_eng,district_eng,unit_type_eng,apartment_type_eng
0,0,77,تبوك - منازل العصرية - درة تبوك,243,115,41,11,المصيف,NaN,1046,50.617284,1,1,28.455361,36.51625,2021-01-25,01-11-0003,0.0,NaN,11-1104-2608-05-00000000802,267922.79796,330190.0,T5,T5-D-G-2,D,152.5,19.76,0,NaN,شقة,3,4,0,0,نموذج 3-3,شقة,1,3.0,18.7,16.0,8.8,23.0,267922.79796,1,1,1,0,0,0,Tabuk - Modern Homes - Durat Tabuk,Summer,Apartment,Apartment
1,1,77,تبوك - منازل العصرية - درة تبوك,243,115,41,11,المصيف,NaN,1046,50.617284,1,1,28.455361,36.51625,2021-01-25,01-11-0003,0.0,NaN,11-1104-2608-05-00000000813,305695.52029,376638.0,T5,T5-D-3-13,D,174.0,21.92,3,NaN,شقة,3,4,0,0,نموذج 3-3,شقة,1,3.0,18.7,13.6,8.8,15.6,344023.00000,1,1,1,0,0,0,Tabuk - Modern Homes - Durat Tabuk,Summer,Apartment,Apartment
2,2,77,تبوك - منازل العصرية - درة تبوك,243,115,41,11,المصيف,NaN,1046,50.617284,1,1,28.455361,36.51625,2021-01-25,01-11-0003,0.0,NaN,11-1104-2608-05-00000000817,305695.52029,376638.0,T5,T5-D-4-17,D,174.0,21.92,4,NaN,شقة,3,4,0,0,نموذج 3-3,شقة,1,3.0,18.7,13.6,8.8,15.6,305695.52029,1,1,1,0,0,0,Tabuk - Modern Homes - Durat Tabuk,Summer,Apartment,Apartment
3,3,77,تبوك - منازل العصرية - درة تبوك,243,115,41,11,المصيف,NaN,1046,50.617284,1,1,28.455361,36.51625,2021-01-25,01-11-0003,0.0,NaN,11-1104-2608-05-00000000821,305695.52029,376638.0,T5,T5-D-5-21,D,174.0,21.92,5,NaN,شقة,3,4,0,0,نموذج 3-3,شقة,1,3.0,18.7,13.6,8.8,15.6,305695.52029,1,1,1,0,0,0,Tabuk - Modern Homes - Durat Tabuk,Summer,Apartment,Apartment
4,4,77,تبوك - منازل العصرية - درة تبوك,243,115,41,11,المصيف,NaN,1046,50.617284,1,1,28.455361,36.51625,2021-01-25,01-11-0003,0.0,NaN,11-1104-2608-05-00000000825,305695.52029,376638.0,T5,T5-D-6-25,D,174.0,21.92,6,NaN,شقة,3,4,0,0,نموذج 3-3,شقة,1,3.0,18.7,13.6,8.8,15.6,305695.52029,1,1,1,0,0,0,Tabuk - Modern Homes - Durat Tabuk,Summer,Apartment,Apartment

In [32]:
translated_file = pd.read_csv(r"C:\Users\rahul\Desktop\Offshore\PubSec-Info-Assistant-Offshore\data\translated_file.csv")
translated_file.head()

,Unnamed: 0,project_id,project_name,TotalUnitsCount,AvailableUnitsCount,city_id,region_id,district,property_year_of_built,BookingsCount,PercentageUnitsBooked,active_payment_by_cash,active_payment_by_loan,project_latitude,project_longitude,publish_date,code,completion_percentage,mega_project_id,unit_code,moh_price,price,block_number,apartment_number,building_number,unit_size,living_area,floor,floor_count,unit_type,bedroom_count,bathroom_count,selections_count,bookings_count,comment,apartment_type,zone_number,number_of_rooms,master_bedroom_size,living_room_size,kitchen_size,guestroom_size,FirstPrice,partners,web,mobile,beneficiary,non_bene,construction_status,project_name_eng,district_eng,unit_type_eng,apartment_type_eng
0,0,77,تبوك - منازل العصرية - درة تبوك,243,115,41,11,المصيف,NaN,1046,50.617284,1,1,28.455361,36.51625,2021-01-25,01-11-0003,0.0,NaN,11-1104-2608-05-00000000802,267922.79796,330190.0,T5,T5-D-G-2,D,152.5,19.76,0,NaN,شقة,3,4,0,0,نموذج 3-3,شقة,1,3.0,18.7,16.0,8.8,23.0,267922.79796,1,1,1,0,0,0,Tabuk - Modern Homes - Durat Tabuk,Summer,Apartment,Apartment
1,1,77,تبوك - منازل العصرية - درة تبوك,243,115,41,11,المصيف,NaN,1046,50.617284,1,1,28.455361,36.51625,2021-01-25,01-11-0003,0.0,NaN,11-1104-2608-05-00000000813,305695.52029,376638.0,T5,T5-D-3-13,D,174.0,21.92,3,NaN,شقة,3,4,0,0,نموذج 3-3,شقة,1,3.0,18.7,13.6,8.8,15.6,344023.00000,1,1,1,0,0,0,Tabuk - Modern Homes - Durat Tabuk,Summer,Apartment,Apartment
2,2,77,تبوك - منازل العصرية - درة تبوك,243,115,41,11,المصيف,NaN,1046,50.617284,1,1,28.455361,36.51625,2021-01-25,01-11-0003,0.0,NaN,11-1104-2608-05-00000000817,305695.52029,376638.0,T5,T5-D-4-17,D,174.0,21.92,4,NaN,شقة,3,4,0,0,نموذج 3-3,شقة,1,3.0,18.7,13.6,8.8,15.6,305695.52029,1,1,1,0,0,0,Tabuk - Modern Homes - Durat Tabuk,Summer,Apartment,Apartment
3,3,77,تبوك - منازل العصرية - درة تبوك,243,115,41,11,المصيف,NaN,1046,50.617284,1,1,28.455361,36.51625,2021-01-25,01-11-0003,0.0,NaN,11-1104-2608-05-00000000821,305695.52029,376638.0,T5,T5-D-5-21,D,174.0,21.92,5,NaN,شقة,3,4,0,0,نموذج 3-3,شقة,1,3.0,18.7,13.6,8.8,15.6,305695.52029,1,1,1,0,0,0,Tabuk - Modern Homes - Durat Tabuk,Summer,Apartment,Apartment
4,4,77,تبوك - منازل العصرية - درة تبوك,243,115,41,11,المصيف,NaN,1046,50.617284,1,1,28.455361,36.51625,2021-01-25,01-11-0003,0.0,NaN,11-1104-2608-05-00000000825,305695.52029,376638.0,T5,T5-D-6-25,D,174.0,21.92,6,NaN,شقة,3,4,0,0,نموذج 3-3,شقة,1,3.0,18.7,13.6,8.8,15.6,305695.52029,1,1,1,0,0,0,Tabuk - Modern Homes - Durat Tabuk,Summer,Apartment,Apartment

In [16]:
print(f"There are total **{df.project_id.nunique()}** distinct projects in database")
print(f"The shape of dataset is {df.shape}")#, df.shape

There are total **127** distinct projects in database
The shape of dataset is (5000, 48)

In [20]:
print(df.project_id.value_counts(normalize=True).head())

project_id
1227    0.1260
1040    0.0654
1137    0.0606
16      0.0554
1142    0.0520
Name: proportion, dtype: float64

In [21]:
df.project_id.value_counts().tail()

project_id
1153    1
1150    1
1066    1
1144    1
704     1
Name: count, dtype: int64

## Checking the missing values

{'project_id': 0,
 'project_name_eng': 0,
 'TotalUnitsCount': 0,
 'AvailableUnitsCount': 0,
 'city_id': 0,
 'region_id': 0,
 'district_eng': 0,
 'property_year_of_built': 3605,
 'BookingsCount': 0,
 'PercentageUnitsBooked': 0,
 'active_payment_by_cash': 0,
 'active_payment_by_loan': 0,
 'project_latitude': 125,
 'project_longitude': 125,
 'publish_date': 0,
 'code': 0,
 'completion_percentage': 0,
 'mega_project_id': 2915,
 'unit_code': 0,
 'moh_price': 0,
 'price': 0,
 'block_number': 0,
 'apartment_number': 2787,
 'building_number': 2787,
 'unit_size': 0,
 'living_area': 0,
 'floor': 0,
 'floor_count': 633,
 'unit_type_eng': 0,
 'bedroom_count': 0,
 'bathroom_count': 0,
 'selections_count': 0,
 'bookings_count': 0,
 'comment': 4373,
 'apartment_type_eng': 0,
 'zone_number': 1821,
 'number_of_rooms': 704,
 'master_bedroom_size': 708,
 'living_room_size': 708,
 'kitchen_size': 709,
 'guestroom_size': 708,
 'FirstPrice': 41,
 'partners': 0,
 'web': 0,
 'mobile': 0,
 'beneficiary': 0,
 'non_bene': 0,
 'construction_status': 0}